FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8000

COPY package*.json ./
RUN npm ci --omit=dev \
  && npm cache clean --force

COPY dist ./dist

EXPOSE 8000
CMD ["node", "dist/src/main.js"]
